apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: korede01/portfolio:my-website
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-website-service
spec:
  type: LoadBalancer 
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 80

